# print("Hello World")
# print("Hekko World")
# print("Hello World")
# print("Hello World")
# print("Hello World Test")
# print("hello world")
Name = input("Please type your Name: ")
age = int(input("Please now your age: "))
print(Name)
print(Name + " is " + str(age) + " years old")
print(f"{Name} is {age} years old")
